=== brenapp/referee.fyi/public/rules/schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema#",
  "$id": "https://referee.fyi/rules/schema.json",
  "title": "Referee FYI Game Schema",
  "description": "Describes the shape of Referee FYI game descriptions.",
  "type": "object",
  "required": ["title", "season", "programs", "ruleGroups"],
  "properties": {
    "title": {
      "type": "string",
      "description": "The game name."
    },
    "season": {
      "type": "string",
      "description": "The year (ex. 2024-2025) that the game applies to."
    },
    "programs": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/program"
      },
      "description": "The programs that the game is for."
    },
    "ruleGroups": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/ruleGroup"
      },
      "description": "The rule groups in the game."
    }
  },
  "$defs": {
    "program": {
      "enum": ["V5RC", "VURC", "VAIRC", "VIQRC", "ADC"],
      "description": "The program abbreviation."
    },
    "ruleGroup": {
      "required": ["name", "programs", "rules"],
      "properties": {
        "name": {
          "type": "string",
          "description": "The rule group name."
        },
        "programs": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/program"
          },
          "description": "The programs that the rule group is for."
        },
        "rules": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/rule"
          },
          "description": "The rules in the group."
        }
      }
    },
    "rule": {
      "required": ["rule", "description", "link"],
      "properties": {
        "rule": {
          "type": "string",
          "description": "The rule code, like <SG4>`"
        },
        "description": {
          "type": "string",
          "description": "Single-sentence quick-description of rule."
        },
        "link": {
          "type": "string",
          "format": "uri",
          "description": "Game manual link to the rule."
        },
        "icon": {
          "type": "string",
          "format": "uri",
          "description": "A link to a small image icon which represents the rule",
          "required": "false"
        }
      }
    }
  }
}

=== brenapp/referee.fyi/public/rules/V5RC/2024-2025.json
{
  "$schema": "https://referee.fyi/rules/schema.json",
  "title": "High Stakes",
  "season": "2024-2025",
  "programs": ["V5RC", "VURC", "VAIRC"],
  "ruleGroups": [
    {
      "name": "Specific Game Rules",
      "programs": ["V5RC", "VURC", "VAIRC"],
      "rules": [
        {
          "rule": "<SG1>",
          "description": "Starting a Match",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/SG1.html"
        },
        {
          "rule": "<SG2>",
          "description": "Horizontal expansion is limited",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/SG2.html"
        },
        {
          "rule": "<SG3>",
          "description": "Vertical expansion is limited",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/SG3.html"
        },
        {
          "rule": "<SG4>",
          "description": "Keep Scoring Objects in the field",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/SG4.html"
        },
        {
          "rule": "<SG5>",
          "description": "Each Robot gets one Ring as a preload",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/SG5.html"
        },
        {
          "rule": "<SG6 - Rings>",
          "description": "Possession is limited to two Rings",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/SG6.html",
          "icon": "/public/icons/High_Stakes_Ring.png"
        },
        {
          "rule": "<SG6 - Goals>",
          "description": "Possession is limited to one Mobile Goal",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/SG6.html",
          "icon": "/public/icons/High_Stakes_Goal.png"
        },
        {
          "rule": "<SG7>",
          "description": "Don't cross the Autonomous Line",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/SG7.html"
        },
        {
          "rule": "<SG8>",
          "description": "Engage with the Autonomous Line at your own risk",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/SG8.html"
        },
        {
          "rule": "<SG9>",
          "description": "Don't remove opponents from the Ladder",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/SG9.html"
        },
        {
          "rule": "<SG10>",
          "description": "Alliance Wall Stakes are protected",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/SG10.html"
        },
        {
          "rule": "<SG11>",
          "description": "Positive Corners are \"safe\" during the endgame.",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/SG11.html"
        }
      ]
    },
    {
      "name": "VURC General Rules",
      "programs": ["VURC", "VAIRC"],
      "rules": [
        {
          "rule": "<VUG1>",
          "description": "Different expansion",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/VUG1.html"
        },
        {
          "rule": "<VUG2>",
          "description": "Different climbing",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/VUG2.html"
        },
        {
          "rule": "<VUG3>",
          "description": "Different autonomous",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/VUG3.html"
        }
      ]
    },
    {
      "name": "General Rules",
      "programs": ["V5RC", "VURC", "VAIRC"],
      "rules": [
        {
          "rule": "<G1>",
          "description": "Treat everyone with respect",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/G1.html"
        },
        {
          "rule": "<G2>",
          "description": "V5RC is a student-centered program",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/G2.html"
        },
        {
          "rule": "<G3>",
          "description": "Use common sense",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/G3.html"
        },
        {
          "rule": "<G4>",
          "description": "The Robot must represent the skill level of the Team",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/G4.html"
        },
        {
          "rule": "<G5>",
          "description": "Robots begin the Match in the starting volume",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/G5.html"
        },
        {
          "rule": "<G6>",
          "description": "Keep your Robots together",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/G6.html"
        },
        {
          "rule": "<G7>",
          "description": "Don't clamp your Robot to the Field",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/G7.html"
        },
        {
          "rule": "<G8>",
          "description": "Only Drive Team Members, and only in the Alliance Station",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/G8.html"
        },
        {
          "rule": "<G9>",
          "description": "Hands out of the field",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/G9.html"
        },
        {
          "rule": "<G10>",
          "description": "Controllers must stay connected to the field",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/G10.html"
        },
        {
          "rule": "<G11>",
          "description": "Autonomous means “no humans",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/G11.html"
        },
        {
          "rule": "<G12>",
          "description": "All rules still apply in the Autonomous Period",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/G12.html"
        },
        {
          "rule": "<G13>",
          "description": "Don't destroy other Robots",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/G13.html"
        },
        {
          "rule": "<G14>",
          "description": "Offensive Robots get the “benefit of the doubt",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/G14.html"
        },
        {
          "rule": "<G15>",
          "description": "You can't force an opponent into a penalty",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/G15.html"
        },
        {
          "rule": "<G16>",
          "description": "No Holding for more than a 5-count",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/G16.html"
        },
        {
          "rule": "<G17>",
          "description": "Use Scoring Objects to play the game",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/G17.html"
        }
      ]
    },
    {
      "name": "Safety Rules",
      "programs": ["V5RC", "VURC", "VAIRC"],
      "rules": [
        {
          "rule": "<S1>",
          "description": "Be safe out there",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/S1.html"
        },
        {
          "rule": "<S2>",
          "description": "Students must be accompanied by an Adult",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/S2.html"
        },
        {
          "rule": "<S3>",
          "description": "Stay inside the field",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/S3.html"
        },
        {
          "rule": "<S4>",
          "description": "Wear safety glasses",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/S4.html"
        }
      ]
    },
    {
      "name": "VURC Robot Rules",
      "programs": ["VURC", "VAIRC"],
      "rules": [
        {
          "rule": "<VUR1>",
          "description": "Teams may use two (2) Robots in each Match",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/VUR1.html"
        },
        {
          "rule": "<VUR2>",
          "description": "Teams may use any official VEX Robotics products, other than the exceptions listed in the tables below, to construct their Robot",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/VUR2.html"
        },
        {
          "rule": "<VUR3>",
          "description": "Fabricated Parts may be made by applying the following manufacturing processes to legal Raw Stock:",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/VUR3.html"
        },
        {
          "rule": "<VUR4>",
          "description": "Fabricated Parts must be made from legal Raw Stock",
          "link": "https://www.robotevents.com/storage/game_manual/V5RC_2024-2025_High_Stakes/rules/VUR4.html"
        },
        {
          "rule": "<VUR5>",
          "description": "The following material types are not considered Raw Stock, and are therefore not permitted:",
